# Generated by Django 5.2.7 on 2026-04-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_socio', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('obra_social', models.CharField(choices=[('OSDE', 'OSDE'), ('OSEP', 'OSEP'), ('Swiss Medical', 'Swiss Medical'), ('Medicus', 'Medicus'), ('Galeno', 'Galeno'), ('IOMA', 'IOMA'), ('Particular', 'Particular'), ('Otro', 'Otro')], default='Particular', max_length=30)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
