# Generated by Django 5.2.7 on 2026-04-27 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('especialidad', models.CharField(blank=True, max_length=50)),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo de consulta')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('evolucion', models.TextField(blank=True, verbose_name='Evolución / Observaciones')),
                ('tratamiento', models.TextField(blank=True, verbose_name='Tratamiento indicado')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='historias_clinicas/%Y/%m/')),
                ('es_mas_reciente', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pacientes.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='profesionales.profesional')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Historial Clínico',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
