# Generated by Django 5.2.7 on 2026-04-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('matricula_nacional', models.CharField(max_length=20, unique=True)),
                ('matricula_provincial', models.CharField(blank=True, max_length=20)),
                ('especialidad', models.CharField(choices=[('Clínica Médica', 'Clínica Médica'), ('Cardiología', 'Cardiología'), ('Pediatría', 'Pediatría'), ('Ginecología', 'Ginecología'), ('Neurología', 'Neurología'), ('Traumatología', 'Traumatología'), ('Kinesiología', 'Kinesiología'), ('Psicología', 'Psicología'), ('Odontología', 'Odontología'), ('Dermatología', 'Dermatología'), ('Oftalmología', 'Oftalmología'), ('Otro', 'Otro')], max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profesionales/')),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
